---
- name: Remove BeSman
  become: yes
  #become_user: "{{ lookup('ansible.builtin.env', 'USER')|default('nobody', True) }}"
  become_user: vagrant
  file:
    path: /{{ ansible_env.HOME }}/.besman
    state: absent
