---
- debug:
    msg: "oah-update of bes.shell"
# Self update oah-shell based on VERSION or brute if the force update config is set to true

- name: Update BeSman
  include_tasks: oah-install-besman.yml
  ignore_errors: true